---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Checkout project repository
      ansible.builtin.git:
        repo: {{ repository }}
        dest: /tmp/ansible/{{ projectName }}