---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Checkout project repository
      ansible.builtin.git:
        repo: '{{ repository }}'
        dest: '/tmp/ansible/{{ projectName }}'
    - name: Build docker image
      docker_image:
        name: '{{ projectName }}'
        source: build
        build:
          path: '/tmp/ansible/{{ projectName }}'
        force: true
        tag: latest
